### ISSUE TITLE
部署配置里是不是少了个bot.py的修改？

### ISSUE THREAD

**Issue by moian98** [mobyw/nonebot-general-rss#4]
ELF_RSS里有这个
![QQ截图20220123141515](https://user-images.githubusercontent.com/56097585/150667085-5861d818-37ab-4873-9f84-84529dcc1119.png)
大佬你这个是一样的添加那个代码吗？还是另外的？
`nonebot.load_plugin("nonebot_plugin_apscheduler") # 加上此行代码`

**Comment by mobyw** [comment]
这个插件是使用 `nonebot.require()` 方法进行导入的，无需额外的 `nonebot.load_plugin()`
我测试时候没有加也是可用正常运行的。

**Comment by moian98** [comment]
> 这个是使用`nonebot.require()`方法进行导入的，不需要额外的`nonebot.load_plugin()` 我测试的时候没有添加正常运行的插件。

找到原因了，我用的是nonebot2.0.0b1，不知道为什么读取不了插件名，把你这个插件里的`cqhttp`修改为`onebot.v11`就能正常用了。

**Comment by mobyw** [comment]
> 找到原因了，我用的是nonebot2.0.0b1，不知道为什么读取不了插件名，把你这个插件里的`cqhttp`修改为`onebot.v11`就能正常用了。

插件 `2.0.0` 版本已适配 `nonebot2@2.0.0b1` ，可以用 `main` 分支最新的代码覆盖一下。

**Comment by moian98** [comment]
是我小白了，谢谢。
